import type { Metadata } from "next";
import GlobalFooter from "@/components/global/GlobalFooter";
import Globalheader from "@/components/global/GlobalHeader";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Globalheader />
        {children}
        <GlobalFooter />
      </body>
    </html>
  );
}
